# Generated by Django 3.0.14 on 2021-12-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoltageSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(verbose_name='Date and time of the measurement:')),
                ('current_voltage', models.DecimalField(decimal_places=2, default=20, max_digits=8, verbose_name='Voltage measurement value:')),
                ('is_error', models.BooleanField(default=False, verbose_name='Activeness')),
                ('ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='IP')),
            ],
        ),
    ]
