# Generated by Django 3.0.14 on 2021-12-11 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task2_main', '0002_auto_20211203_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_voltage', models.DecimalField(decimal_places=2, default=20, max_digits=8, verbose_name='Voltage measurement value:')),
                ('is_error', models.BooleanField(default=False, verbose_name='Activeness')),
                ('time_where_sensor', models.DateTimeField(verbose_name='Date and time of the measurement:')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email was sent')),
            ],
        ),
        migrations.CreateModel(
            name='ValidatedMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in_poland', models.DateTimeField(verbose_name='Date and time of the measurement:')),
                ('current_voltage', models.DecimalField(decimal_places=2, default=20, max_digits=8, verbose_name='Voltage measurement value:')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task2_main.VoltageSensor', verbose_name='VoltageSensor')),
            ],
        ),
    ]
