# Generated by Django 3.0.14 on 2021-12-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task2_main', '0003_invalidmeasurement_validatedmeasurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='time_stamp',
        ),
    ]
